language: generic
sudo: false
cache:
  apt: true
  directories:
    - /tmp/tools
env:
  global:
    - PATH="$HOME/bin:$PATH"
    - CMAKE_VERSION_PREFIX=3.8
    - CMAKE_VERSION_FULL=3.8.0
    - NINJA_VERSION=1.7.2
matrix:
  include:
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - gcc-7
            - unzip
            - xorg-dev
            - libgl1-mesa-dev
          sources: &sources
            - r-packages-precise
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-5.0
    - env: CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          packages:
            - clang-5.0
            - libc++-dev
            - unzip
            - xorg-dev
            - libgl1-mesa-dev
          sources: *sources
install:
  - mkdir -p /tmp/tools; pushd /tmp/tools
  - if [[ ! -f "cmake-$CMAKE_VERSION_FULL-Linux-x86_64.sh" ]]; then
      curl -SOL "https://cmake.org/files/v$CMAKE_VERSION_PREFIX/cmake-$CMAKE_VERSION_FULL-Linux-x86_64.sh";
      chmod +x "cmake-$CMAKE_VERSION_FULL-Linux-x86_64.sh";
    fi
  - ./"cmake-$CMAKE_VERSION_FULL-Linux-x86_64.sh" --prefix="$HOME" --exclude-subdir --skip-license
  -
  - if [[ ! -f "ninja-$NINJA_VERSION.zip" ]]; then
      curl -SLO "https://github.com/ninja-build/ninja/releases/download/v$NINJA_VERSION/ninja-linux.zip";
      mv "ninja-linux.zip" "ninja-$NINJA_VERSION.zip";
    fi
  - unzip "ninja-$NINJA_VERSION.zip" -d "$HOME/bin"; popd
script:
  - mkdir build && cd build
  - cmake -GNinja ..
  - ninja
